language: rust

rust:
    - nightly

os:
  - linux
  - osx
  - windows

cache:
  directories:
    - $HOME/.cargo

addons:
  apt:
    packages:
      - qemu-system-x86
  homebrew:
    packages:
      - qemu
    update: true

install:
  - if [ $TRAVIS_OS_NAME = windows ]; then choco install qemu; export PATH="/c/Program Files/qemu:$PATH"; fi
  - qemu-system-x86_64 --version

before_script:
  - rustup component add rust-src llvm-tools-preview
  - cargo install bootimage cargo-xbuild cargo-cache --debug -Z install-upgrade

script:
  - cargo xbuild
  - cargo bootimage
  - cargo xtest
  - cargo cache --autoclean
