[package]
name = "ddos_drivers"
version = "0.1.0"
authors = ["Matt Taylor"]
edition = "2018"

[dependencies]
lazy_static = { version = "1", features = ["spin_no_std"] }
ddos_ds = { path = "../ddos_ds" }
